server:
  port: 8080

spring:
  application:
    name: vendor-authentication-service
  
  # SQL Server Configuration
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=vendorauth;encrypt=true;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: your_strong_password
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  
  # MyBatis Configuration
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.vendorauth.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-handlers-package: com.vendorauth.mybatis.typehandler

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET:your-512-bit-secret-make-sure-to-change-this-in-production}
    expiration: 86400000  # 24 hours in milliseconds
    refresh-expiration: 604800000  # 7 days in milliseconds
    issuer: vendor-auth-service
    header: Authorization
    token-prefix: "Bearer "

# Auth Signing Configuration (Keystore-based JWT signing)
auth:
  signing:
    keystore: classpath:keystore/auth-jwt.p12
    store-password: ${KEYSTORE_PASSWORD:changeit}
    key-password: ${KEY_PASSWORD:changeit}
    type: PKCS12
    active-alias: auth-key
    previous-alias: # Optional: for key rotation
    kid: # Optional: override key ID

# Logging Configuration
logging:
  level:
    com.vendorauth: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    io.jsonwebtoken: WARN  # Reduce JWT library logging

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
      roles: ADMIN

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    filter: true

# Security Configuration
security:
  jwt:
    secret: ${app.jwt.secret}
    expiration: ${app.jwt.expiration}
    refresh-expiration: ${app.jwt.refresh-expiration}
